# Generated by Django 3.1 on 2020-08-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newuserapp', '0002_auto_20200825_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='displayname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='new_user',
            name='homepage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
