# Generated by Django 3.1 on 2020-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newuserapp', '0003_auto_20200825_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user',
            name='homepage',
        ),
        migrations.AddField(
            model_name='new_user',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
